services:
  aliddns:
    image: naturelr/aliddns:latest
    container_name: aliddns
    environment:
      - ALIDDNS_KEY=<KERY
      - ALIDDNS_CERT=<CERT>
      - ALIDDNS_DOMAIN=<DOMAIN>
      #- ALIDDNS_CRON=
    restart: always
